name = "maiga-social"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "public"
binding = "ASSETS"

[observability]
enabled = true

[vars]
BACKEND_URL = "YOUR_ACTUAL_DEPLOYED_EXPRESS_APP_URL" # <--- FIX THIS

[[kv_namespaces]]
binding = "KV"
id = "6cbcd3bde4ea4ab5acdf325cbdf9da00"
# preview_id = "YOUR_PREVIEW_ID" # Optional: Used for local development