name = "maiga-social"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[assets]
# This points to the current directory. 
# Wrangler will use your .wranglerignore to skip node_modules.
directory = "."
binding = "ASSETS"

[observability]
enabled = true