name = "maiga-social"
main = "index.js"
compatibility_date = "2026-03-27"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "public"
binding = "ASSETS"

[observability]
enabled = true

[vars]
BACKEND_URL = "https://maiga-social-production.up.railway.app"

[[kv_namespaces]]
binding = "KV"
id = "6cbcd3bde4ea4ab5acdf325cbdf9da00"
# preview_id = "YOUR_PREVIEW_ID" # Optional: Used for local development